export {
  generateId,
  createTables,
  initMockData,
  users,
  receipts,
  embalmingTasks,
  farewellHalls,
  farewellReservations,
  cremationFurnaces,
  cremationTasks,
  storageNiches,
  storageContracts,
  vehicles,
  vehicleTasks,
  notifications,
  dailyReports,
} from './memoryStore.js'

export type {
  User,
  Receipt,
  EmbalmingTask,
  FarewellHall,
  FarewellReservation,
  CremationFurnace,
  CremationTask,
  StorageNiche,
  StorageContract,
  Vehicle,
  VehicleTask,
  Notification,
  DailyReport,
  MemoryStore,
} from './memoryStore.js'
